stages:
  mystage:
    cmd: python train.py
    deps:
    - data
    - train.py
    metrics:
    - metrics.txt:
        cache: false
    plots:
    - confusion_matrix.png:
        cache: false